# -*- coding: utf-8 -*-
"""Lọc dữ liệu sQC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nvKfi1qh9CZdF89QNSm1e5hHmlKzvwxS
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd

df=pd.read_csv('full qGC dataset.csv')

df=df[['Molecule ChEMBL ID','Smiles','pChEMBL Value']]
df=df.dropna()

df = df.groupby('Molecule ChEMBL ID').agg({
    'Smiles': 'first',
    'pChEMBL Value': 'mean'
}).reset_index()

df = df.drop_duplicates(subset='Molecule ChEMBL ID', keep='first').reset_index(drop=True)

df = df.sort_values(by='pChEMBL Value', ascending=True).reset_index(drop=True)
df

from rdkit import Chem

def is_salt(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    frags = Chem.GetMolFrags(mol)
    return len(frags) > 1

df["is_salt"] = df["Smiles"].apply(is_salt)

df

!pip install rdkit

# PHẦN 1: HÀM CHỨC NĂNG ĐỂ CHIA DỮ LIỆU THEO SCAFFOLD
# ==============================================================================
import pandas as pd
from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold
from collections import defaultdict
import random
def generate_scaffold(smiles, include_chirality=False):
    """
    Tạo Murcko Scaffold từ một chuỗi SMILES.
    Trả về SMILES của scaffold.
    """
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return None
        scaffold = MurckoScaffold.GetScaffoldForMol(mol)
        return Chem.MolToSmiles(scaffold, isomericSmiles=include_chirality)
    except:
        return None

def scaffold_split(df, smiles_col='Smiles', frac_train=0.8, frac_val=0.1, frac_test=0.1, seed=42):

    # Đảm bảo tổng tỷ lệ ~ 1.0
    assert (frac_train + frac_val + frac_test) > 0.99 and (frac_train + frac_val + frac_test) < 1.01

    # Tạo scaffold cho mỗi SMILES
    df['scaffold'] = df[smiles_col].apply(generate_scaffold)

    # Loại bỏ các dòng không thể tạo scaffold (ví dụ: SMILES không hợp lệ)
    df = df.dropna(subset=['scaffold']).reset_index(drop=True)

    # Nhóm các chỉ số (index) của phân tử theo scaffold
    scaffolds = defaultdict(list)
    for i, scaffold in enumerate(df['scaffold']):
        scaffolds[scaffold].append(i)

    # Xáo trộn danh sách các scaffold để đảm bảo tính ngẫu nhiên khi chia
    scaffold_list = list(scaffolds.values())
    random.seed(seed)
    random.shuffle(scaffold_list)

    # Tính toán số lượng phân tử mục tiêu cho mỗi tập
    n_total = len(df)
    n_train = int(frac_train * n_total)
    n_val = int(frac_val * n_total)

    # Phân chia chỉ số vào các tập
    train_idx, val_idx, test_idx = [], [], []

    for group in scaffold_list:
        if len(train_idx) + len(group) <= n_train:
            train_idx.extend(group)
        elif len(val_idx) + len(group) <= n_val:
            val_idx.extend(group)
        else:
            test_idx.extend(group)

    # Tạo các DataFrame cuối cùng
    df_train = df.iloc[train_idx].drop(columns=['scaffold'])
    df_val = df.iloc[val_idx].drop(columns=['scaffold'])
    df_test = df.iloc[test_idx].drop(columns=['scaffold'])

    return df_train, df_val, df_test

print("Bắt đầu chia dữ liệu theo scaffold...")
df_train, df_val, df_test = scaffold_split(
    df,
    smiles_col='Smiles',
    frac_train=0.8,
    frac_val=0.1,
    frac_test=0.1
)
print("Chia dữ liệu hoàn tất!")
print("-" * 50)

# --- BƯỚC 3: In kết quả ---
print(f"Số lượng phân tử trong tập train: {len(df_train)} (~{len(df_train)/len(df):.0%})")
print(f"Số lượng phân tử trong tập validation: {len(df_val)} (~{len(df_val)/len(df):.0%})")
print(f"Số lượng phân tử trong tập test: {len(df_test)} (~{len(df_test)/len(df):.0%})")
print("-" * 50)

print("5 dòng đầu của tập train:")
print(df_train.head())

def summarize_pchembl(df, name):
    print(f"\n{name}")
    print("N =", len(df))
    print(df["pChEMBL Value"].describe())

summarize_pchembl(df_train, "TRAIN")
summarize_pchembl(df_val,   "VAL")
summarize_pchembl(df_test,  "TEST")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,6))

sns.kdeplot(df_train["pChEMBL Value"], label="Train", linewidth=2)
sns.kdeplot(df_val["pChEMBL Value"],   label="Val", linewidth=2)
sns.kdeplot(df_test["pChEMBL Value"],  label="Test", linewidth=2)

plt.xlabel("pChEMBL Value")
plt.ylabel("Density")
plt.title("Distribution of pChEMBL after Scaffold Split")
plt.legend()
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

plt.figure(figsize=(6,5))

plt.boxplot(
    [
        df_train["pChEMBL Value"],
        df_val["pChEMBL Value"],
        df_test["pChEMBL Value"]
    ],
    labels=["Train", "Val", "Test"],
    showfliers=True
)

plt.ylabel("pChEMBL Value")
plt.title("pChEMBL Distribution after Scaffold Split")
plt.grid(alpha=0.3)
save_fig_path = "/content/drive/MyDrive/data_distribution_pChEMBL.png"

plt.tight_layout()

# -------- SAVE THE FIGURE HERE --------
plt.savefig(save_fig_path, dpi=300, bbox_inches='tight')   # chỉnh dpi tại đây
plt.show()

from scipy.stats import ks_2samp

print("Train vs Test:",
      ks_2samp(df_train["pChEMBL Value"], df_test["pChEMBL Value"]))

print("Train vs Val:",
      ks_2samp(df_train["pChEMBL Value"], df_val["pChEMBL Value"]))

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import matplotlib.pyplot as plt

groups = [df_train['pChEMBL Value'].values, df_val['pChEMBL Value'].values, df_test['pChEMBL Value'].values]
labels = ['Train', 'Val', 'Test']
colors = ['#1f77b4', '#ffbf00', '#d62728']

plt.figure(figsize=(10,7))
bp = plt.boxplot(groups,
                 patch_artist=True,
                 widths=0.6,
                 showfliers=False,
                 medianprops=dict(color='black'),
                 labels=labels)

# Color the boxes
for patch, color in zip(bp['boxes'], colors):
    patch.set_facecolor(color)
    patch.set_edgecolor('black')
    patch.set_linewidth(1)

# Style whiskers and caps
for whisker in bp['whiskers']:
    whisker.set(color='black', linewidth=1)
for cap in bp['caps']:
    cap.set(color='black', linewidth=1)

# Move sample count UNDER the median line
for i, arr in enumerate(groups):
    ymin, ymax = np.min(arr), np.max(arr)
    med = np.median(arr)
    offset = (ymax - ymin) * 0.10  # 10% below median

    plt.text(i+1, med - offset,
             f"n = {len(arr)}",
             ha='center', va='center',
             color='white',
             fontsize=12, fontweight='bold')

# Labels, title
plt.ylabel('pChEMBL Value', fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)

# Cleaner frame
ax = plt.gca()
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

save_fig_path = "/content/drive/MyDrive/data_distribution_sQC.png"

plt.tight_layout()

# -------- SAVE THE FIGURE HERE --------
plt.savefig(save_fig_path, dpi=300, bbox_inches='tight')   # chỉnh dpi tại đây
# --------------------------------------

plt.show()

train_filename = 'train_scaffold_split.csv'
val_filename = 'validation_scaffold_split.csv'
test_filename = 'test_scaffold_split.csv'

df_train.to_csv(train_filename, index=False)
df_val.to_csv(val_filename, index=False)
df_test.to_csv(test_filename, index=False)
print(f"Đã lưu thành công 3 files:")
print(f"- {train_filename} ({len(df_train)} dòng)")
print(f"- {val_filename} ({len(df_val)} dòng)")
print(f"- {test_filename} ({len(df_test)} dòng)")
print("-" * 50)
print("Bắt đầu quá trình tải file xuống. Vui lòng đợi...")
files.download(train_filename)
files.download(val_filename)
files.download(test_filename)
print("Hoàn tất! Kiểm tra thư mục Downloads trên máy tính của bạn.")

from sklearn.model_selection import train_test_split
train_df, temp_df = train_test_split(df, test_size=0.2, random_state=42)
val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)
print(f"Train: {len(train_df)}, Validation: {len(val_df)}, Test: {len(test_df)}")

train_df.to_csv("train_QC.csv", index=False)
val_df.to_csv("validation_QC.csv", index=False)
test_df.to_csv("test_QC.csv", index=False)

print("Đã lưu 3 file: train.csv, validation.csv, test.csv")

from google.colab import files

files.download("train_QC.csv")
files.download("validation_QC.csv")
files.download("test_QC.csv")