# -*- coding: utf-8 -*-
"""train.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gWU2KWQLvwZMu8F4murnlFDaS5y5KL_u
"""

!pip install transformers rdkit pandas scikit-learn torch

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel, get_linear_schedule_with_warmup
from rdkit import Chem
from rdkit.Chem import AllChem
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from torch.optim import AdamW

from google.colab import files
uploaded=files.upload()

tokenizer = AutoTokenizer.from_pretrained("seyonec/ChemBERTa-zinc-base-v1")

def tokenize(smiles_list):
    return tokenizer(
        list(smiles_list),
        padding='max_length',
        truncation=True,
        max_length=128,
        return_tensors='pt'
    )

def smiles_to_morgan_fp(smiles, radius=2, n_bits=2048):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return np.zeros(n_bits)
    return AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits=n_bits)

# ==== Dataset ====
class HybridDataset(Dataset):
    def __init__(self, smiles, labels):
        self.encodings = tokenize(smiles)
        self.fingerprints = torch.tensor(
            [smiles_to_morgan_fp(s) for s in smiles], dtype=torch.float32
        )
        self.labels = torch.tensor(labels, dtype=torch.float32)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item['fingerprint'] = self.fingerprints[idx]
        item['labels'] = self.labels[idx]
        return item

class HybridRegressor(nn.Module):
    def __init__(self, transformer_name="seyonec/ChemBERTa-zinc-base-v1", fingerprint_dim=2048):
        super().__init__()
        self.transformer = AutoModel.from_pretrained(transformer_name)


        self.fp_net = nn.Sequential(
            nn.Linear(fingerprint_dim, 1024),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(1024, 512),
            nn.ReLU()
        )


        emb_dim = self.transformer.config.hidden_size
        self.emb_net = nn.Sequential(
            nn.Linear(emb_dim, 512),
            nn.ReLU(),
            nn.Dropout(0.2)
        )


        self.combined_net = nn.Sequential(
            nn.Linear(512 + 512, 512),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(128,1)
        )

    def forward(self, input_ids, attention_mask, fingerprint, labels=None):
        emb_out = self.transformer(input_ids=input_ids, attention_mask=attention_mask)
        pooled = emb_out.last_hidden_state[:, 0]  # CLS token

        fp_feat = self.fp_net(fingerprint)
        emb_feat = self.emb_net(pooled)

        combined = torch.cat([fp_feat, emb_feat], dim=1)
        logits = self.combined_net(combined)

        output = {'logits': logits}
        if labels is not None:
            loss_fn = nn.MSELoss()
            loss = loss_fn(logits.view(-1), labels.view(-1))
            output['loss'] = loss
        return output

import random
import os
def set_seed(seed: int = 42):
    # Python & NumPy
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

    # Torch
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # CuDNN
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    # worker + generator cho DataLoader
    def seed_worker(worker_id):
        worker_seed = seed + worker_id
        np.random.seed(worker_seed)
        random.seed(worker_seed)

    g = torch.Generator()
    g.manual_seed(seed)

    return seed_worker, g

# ==== Load data ====
train_df = pd.read_csv("train_scaffold_split.csv")
val_df   = pd.read_csv("validation_scaffold_split.csv")

train_dataset = HybridDataset(train_df["Smiles"], train_df["pChEMBL Value"])
val_dataset   = HybridDataset(val_df["Smiles"], val_df["pChEMBL Value"])

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader   = DataLoader(val_dataset, batch_size=16, shuffle=False)

seed_worker, g = set_seed(42)

train_loader = DataLoader(
    train_dataset, batch_size=16, shuffle=True,
    worker_init_fn=seed_worker, generator=g
)
val_loader = DataLoader(
    val_dataset, batch_size=16, shuffle=False,
    worker_init_fn=seed_worker, generator=g
)

from transformers import get_cosine_schedule_with_warmup
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
epochs = 50

model = HybridRegressor().to(device)
optimizer = AdamW(model.parameters(), lr=1e-3, weight_decay=0.01)

total_steps = epochs * len(train_loader)
warmup_steps = int(0.1 * total_steps)

scheduler = get_cosine_schedule_with_warmup(
    optimizer,
    num_warmup_steps=warmup_steps,
    num_training_steps=total_steps
)

def evaluate(loader):
    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch in loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            outputs = model(
                input_ids=batch['input_ids'],
                attention_mask=batch['attention_mask'],
                fingerprint=batch['fingerprint']
            )
            preds = outputs['logits']
            y_true.extend(batch['labels'].cpu().numpy())
            y_pred.extend(preds.squeeze().cpu().numpy())

    mse = mean_squared_error(y_true, y_pred)
    rmse = mse ** 0.5
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    return rmse, mae, r2

best_val_rmse = float('inf')
best_model_state = None
best_train_metrics = None
best_val_metrics = None

for epoch in range(epochs):
    model.train()
    total_loss = 0
    for batch in train_loader:
        batch = {k: v.to(device) for k, v in batch.items()}
        optimizer.zero_grad()
        outputs = model(
            input_ids=batch['input_ids'],
            attention_mask=batch['attention_mask'],
            fingerprint=batch['fingerprint'],
            labels=batch['labels']
        )
        loss = outputs['loss']
        loss.backward()
        optimizer.step()
        scheduler.step()
        total_loss += loss.item()

    # Chỉ đánh giá train và val
    train_metrics = evaluate(train_loader)
    val_metrics = evaluate(val_loader)

    if val_metrics[0] < best_val_rmse:  # val_rmse
        best_val_rmse = val_metrics[0]
        best_model_state = model.state_dict()
        best_train_metrics = train_metrics
        best_val_metrics = val_metrics

    print(f"Epoch {epoch+1}/{epochs}:")
    print(f"  Train - RMSE: {train_metrics[0]:.4f}, MAE: {train_metrics[1]:.4f}, R²: {train_metrics[2]:.4f}")
    print(f"  Valid - RMSE: {val_metrics[0]:.4f}, MAE: {val_metrics[1]:.4f}, R²: {val_metrics[2]:.4f}")

test_df  = pd.read_csv("test_scaffold_split.csv")
test_dataset  = HybridDataset(test_df["Smiles"], test_df["pChEMBL Value"])
test_loader  = DataLoader(test_dataset, batch_size=16, shuffle=False)
test_loader = DataLoader(
    test_dataset, batch_size=16, shuffle=False,
    worker_init_fn=seed_worker, generator=g
)

model.load_state_dict(best_model_state)
test_metrics = evaluate(test_loader)

print(f"\n✅ Best model saved with Val RMSE = {best_val_rmse:.4f}")
print("🔍 Best metrics at best Val RMSE:")
print(f"  ▶ Train - RMSE: {best_train_metrics[0]:.4f}, MAE: {best_train_metrics[1]:.4f}, R²: {best_train_metrics[2]:.4f}")
print(f"  ▶ Valid - RMSE: {best_val_metrics[0]:.4f}, MAE: {best_val_metrics[1]:.4f}, R²: {best_val_metrics[2]:.4f}")
print(f"  ▶ Test  - RMSE: {test_metrics[0]:.4f}, MAE: {test_metrics[1]:.4f}, R²: {test_metrics[2]:.4f}")
